name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew build --no-daemon
